-- MySQL Script generated by MySQL Workbench
-- dom 15 nov 2020 22:40:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`AtoRegulatorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AtoRegulatorio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AtoRegulatorio` (
  `id_AtoRegulatorio` INT NOT NULL AUTO_INCREMENT,
  `documentoMec_AtoRegulatorio` VARCHAR(45) NULL,
  PRIMARY KEY (`id_AtoRegulatorio`),
  UNIQUE INDEX `documentoMec_AtoRegulatorio_UNIQUE` (`documentoMec_AtoRegulatorio` ASC) VISIBLE,
  UNIQUE INDEX `id_AtoRegulatorio_UNIQUE` (`id_AtoRegulatorio` ASC) VISIBLE,
  CONSTRAINT `fk_AtoRegulatorio_1`
    FOREIGN KEY (`id_AtoRegulatorio`)
    REFERENCES `mydb`.`Instituicao` (`id_Instituicao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Curso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `idCurso` INT NOT NULL,
  `descricao_Curso` VARCHAR(45) NULL,
  `modalidade_Curso` VARCHAR(45) NULL,
  `tipo_Curso` VARCHAR(45) NULL,
  `duracao_Curso` VARCHAR(45) NULL,
  `atoRegulatorio_Curso` VARCHAR(45) NULL,
  PRIMARY KEY (`idCurso`),
  CONSTRAINT `fk_Curso_1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `mydb`.`Instituicao` (`id_Instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Disciplina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina` (
  `idDisciplina` INT NOT NULL,
  `nome_Disciplina` VARCHAR(45) NULL,
  `cargaHoraria_Disciplina` VARCHAR(45) NULL,
  PRIMARY KEY (`idDisciplina`),
  CONSTRAINT `fk_Disciplina_1`
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `mydb`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `id_Endereco` INT NOT NULL AUTO_INCREMENT,
  `validacao_Endereco` TINYINT NOT NULL,
  `rua_Endereco` VARCHAR(100) NULL,
  `bairro_Endereco` VARCHAR(100) NULL,
  `numero_Endereco` VARCHAR(5) NULL,
  `cidade_Endereco` VARCHAR(45) NULL,
  `uf_Endereco` VARCHAR(2) NULL,
  `cep_Endereco` VARCHAR(10) NULL,
  PRIMARY KEY (`id_Endereco`),
  UNIQUE INDEX `validacao_Endereco_UNIQUE` (`validacao_Endereco` ASC) VISIBLE,
  UNIQUE INDEX `id_Endereco_UNIQUE` (`id_Endereco` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_1`
    FOREIGN KEY (`id_Endereco`)
    REFERENCES `mydb`.`Instituicao` (`id_Instituicao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GradeCurricular`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GradeCurricular` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GradeCurricular` (
  `idGradeCurricular` INT NOT NULL,
  `periodo_GradeCurricular` VARCHAR(45) NULL,
  PRIMARY KEY (`idGradeCurricular`),
  CONSTRAINT `fk_GradeCurricular_1`
    FOREIGN KEY (`idGradeCurricular`)
    REFERENCES `mydb`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Instituicao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Instituicao` (
  `id_Instituicao` INT NOT NULL AUTO_INCREMENT,
  `cnpj_Instituicao` VARCHAR(45) NULL,
  `id_Reitoria_Instituicao` INT NOT NULL,
  PRIMARY KEY (`id_Instituicao`),
  UNIQUE INDEX `id_Instituicao_UNIQUE` (`id_Instituicao` ASC) VISIBLE,
  UNIQUE INDEX `cnpj_Instituicao_UNIQUE` (`cnpj_Instituicao` ASC) VISIBLE,
  INDEX `fk_Instituicao_1_idx` (`id_Reitoria_Instituicao` ASC) VISIBLE,
  CONSTRAINT `fk_Instituicao_1`
    FOREIGN KEY (`id_Reitoria_Instituicao`)
    REFERENCES `mydb`.`Reitoria` (`id_Reitoria`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reitoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reitoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reitoria` (
  `id_Reitoria` INT NOT NULL AUTO_INCREMENT,
  `nome_Reitoria` VARCHAR(45) NULL,
  `cargo_Reitoria` VARCHAR(45) NULL,
  `cpf_Reitoria` VARCHAR(45) NULL,
  `telefone_Reitoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Reitoria`),
  UNIQUE INDEX `id_Reitoria_UNIQUE` (`id_Reitoria` ASC) VISIBLE,
  UNIQUE INDEX `cpf_Reitoria_UNIQUE` (`cpf_Reitoria` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
